name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        composer_flags: ['', '--prefer-lowest']
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --ignore-platform-req=php
          composer update doctrine/dbal ${{ matrix.composer_flags }}

      - name: Run tests
        run: vendor/bin/pest --coverage --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
